# Generated by Django 5.2 on 2025-04-03 13:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_fabout_fblog_fcontact_fthank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabout",
            name="AboutText",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name="fblog",
            name="BlogText",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name="fcontact",
            name="ContactText",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name="fthank",
            name="ThankText",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
